# Generated by Django 3.1.3 on 2021-03-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=100)),
                ('work_day0', models.BooleanField(blank=True, default=False)),
                ('work_day1', models.BooleanField(blank=True, default=False)),
                ('work_day2', models.BooleanField(blank=True, default=False)),
                ('work_day3', models.BooleanField(blank=True, default=False)),
                ('work_day4', models.BooleanField(blank=True, default=False)),
                ('work_day5', models.BooleanField(blank=True, default=False)),
                ('work_day6', models.BooleanField(blank=True, default=False)),
                ('work_day7', models.BooleanField(blank=True, default=False)),
                ('work_day8', models.BooleanField(blank=True, default=False)),
                ('work_day9', models.BooleanField(blank=True, default=False)),
                ('work_day10', models.BooleanField(blank=True, default=False)),
                ('work_day11', models.BooleanField(blank=True, default=False)),
                ('work_day12', models.BooleanField(blank=True, default=False)),
                ('work_day13', models.BooleanField(blank=True, default=False)),
                ('work_day14', models.BooleanField(blank=True, default=False)),
                ('work_day15', models.BooleanField(blank=True, default=False)),
                ('work_day16', models.BooleanField(blank=True, default=False)),
                ('work_day17', models.BooleanField(blank=True, default=False)),
                ('work_day18', models.BooleanField(blank=True, default=False)),
                ('work_day19', models.BooleanField(blank=True, default=False)),
                ('manager', models.BooleanField(blank=True, default=True)),
                ('employer', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_people', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=1)),
                ('times', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=1)),
                ('manager', models.BooleanField(default=True)),
                ('employer', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
